spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
#      routes:
#      - id: mall-admin
#        uri: lb:/mall-admin
#        predicates:
#        - Path= /admin/**
#        fifters:
#        - StripPrefix=1
#      - id: mall-web
#        uri: lb:/mall-web
#        predicates:
#        - Path= /api/**
#        fifters:
#        - StripPrefix=1